### PR TITLE
Encapsulate NFTestAssert class, rewrite tests (attempt 2)

### PR DESCRIPTION
**Pull request by nwiltsie**
# Description
This is the fixed-up version of #67. I figured out the problem and added an explanation below.

This PR rewrites most of the internals of `NFTestAssert` in a way that is (mostly) invisible to the outside world. This is the key interface change:

```diff
@@ -109,12 +108,9 @@ class NFTestCase:
             self._logger.error(" [ failed ]")
             return False

-        for ass in self.asserts:
+        for assertion in self.asserts:
             try:
-                ass.identify_assertion_files()
-                ass.assert_exists()
-                ass.assert_updated()
-                ass.assert_expected()
+                assertion.perform_assertions()
             except Exception as error:
                 self._logger.error(error.args)
                 self._logger.error(" [ failed ]")
```

The new `perform_assertions()` method hides all of the details of `identify_assertion_files()`, `assert_exists()`, `assert_updated()`, and `assert_expected()`. Decoupling the interface from the implementation details like that makes it easier to test and maintain this code.

In that spirit, I've also re-written all of the tests to test the functionality of the class rather than the implementation details. There are a variety of test fixtures that create an `NFTestAssert` instance pointing to reference and updated files in a temporary directory. The fixtures are parameterized to test the following situations:

* Usage of a custom `script`
* The `actual` file was/wasn't updated after the `NFTestAssert` was created
* There are 0, 1, or 2 files matching the `actual` glob
* There are 0, 1, or 2 files matching the `expect` glob
* The `actual` and `expect` files do/don't have the same content

Those parameters are matched with appropriate [`xfail`](https://docs.pytest.org/en/8.1.x/reference/reference.html#pytest-mark-xfail) marks to confirm that the tests do/don't pass in the expected situations. (Aside: by default `xfail` has `strict=False`, meaning that tests that unexpectedly pass do _not_ raise errors. That is bonkers.)

---

There were two (and only two, I hope) problems with #67. The first was some kind of weirdness around cached file modification times, which I've worked around by delaying the file update time until the test itself is run. 🤞 that works.

The second was that I was (intentionally) applying multiple `xfail`-parameterized markers to tests, each with a different `raises` exception class. I _thought_ those would merge, so that if the test raised any of those exceptions the test would pass. However, they _actually_ work serially, and each marker would complain if any other exception was raised.

It seems that by sheer coincidence I perfectly ordered the arguments to the various fixtures so that the markers were constructed in the same order that the exceptions would be raised... on my machine. Something in the GitHub runner environment caused the fixtures to be constructed in a slightly different order so that the "wrong" exception was raised first.

I could replicate that locally by just swapping the order in which the fixtures were requested. This innocuous change broke 96 tests:

```diff
diff --git a/test/unit/test_NFTestAssert.py b/test/unit/test_NFTestAssert.py
index b3dd3e1..8b114c4 100644
--- a/test/unit/test_NFTestAssert.py
+++ b/test/unit/test_NFTestAssert.py
@@ -108,10 +108,10 @@ def fixture_configured_test(
     tmp_path,
     custom_script,
     method,
-    expect_count,
-    actual_count,
     file_updated,
     file_contents,
+    expect_count,
+    actual_count,
 ):
     """
     A fixture to set up an NFTestAssert referring to a temporary directory.
```

I fixed that with a bunch of refactoring, as well as a [custom `xfailgroup` marker](https://docs.pytest.org/en/8.2.x/example/markers.html#mark-examples) that does what I meant in the first place: after test setup is complete, tests marked with `xfailgroup` get a _single_ `xfail` matching _all_ of the exception types.

# Checklist

- [x] This PR **does *NOT* contain** Protected Health Information [(PHI)](https://ohrpp.research.ucla.edu/hipaa/). A repo may ***need to be deleted*** if such data is uploaded. <br> Disclosing PHI is a ***major problem***[^1] - Even ***a small leak can be costly***[^2].
  
- [x] This PR **does *NOT* contain** germline genetic data[^3], RNA-Seq, DNA methylation, microbiome or other molecular data[^4].

[^1]: [UCLA Health reaches $7.5m settlement over 2015 breach of 4.5m patient records](https://healthitsecurity.com/news/ucla-health-reaches-7.5m-settlement-over-2015-breach-of-4.5m)
[^2]: [The average healthcare data breach costs $2.2 million, despite the majority of breaches releasing fewer than 500 records.](https://www.ponemon.org/local/upload/file/Sixth%20Annual%20Patient%20Privacy%20%26%20Data%20Security%20Report%20FINAL%206.pdf)
[^3]: [Genetic information is considered PHI.](https://www.genome.gov/about-genomics/policy-issues/Privacy#:~:text=In%202013%2C%20as%20required%20by,genetic%20information%20for%20underwriting%20purposes.)
  [Forensic assays can identify patients with as few as 21 SNPs](https://www.sciencedirect.com/science/article/pii/S1525157817305962)
[^4]: [RNA-Seq](https://www.nature.com/articles/ng.2248), [DNA methylation](https://ieeexplore.ieee.org/document/7958619), [microbiome](https://www.pnas.org/doi/pdf/10.1073/pnas.1423854112), or other molecular data can be used to predict genotypes (PHI) and reveal a patient's identity.

- [x] This PR **does *NOT* contain** other non-plain text files, such as: compressed files, images (*e.g.* `.png`, .`jpeg`), `.pdf`, `.RData`, `.xlsx`, `.doc`, `.ppt`, or other output files.

_&emsp; To automatically exclude such files using a [.gitignore](https://docs.github.com/en/get-started/getting-started-with-git/ignoring-files) file, see [here](https://github.com/uclahs-cds/template-base/blob/main/.gitignore) for example._

- [x] I have read the [code review guidelines](https://uclahs-cds.atlassian.net/wiki/spaces/BOUTROSLAB/pages/3187646/Code+Review+Guidelines) and the [code review best practice on GitHub check-list](https://uclahs-cds.atlassian.net/wiki/spaces/BOUTROSLAB/pages/3189956/Code+Review+Best+Practice+on+GitHub+-+Check+List).

- [x] I have set up or verified the `main` branch protection rule following the [github standards](https://uclahs-cds.atlassian.net/wiki/spaces/BOUTROSLAB/pages/3190380/GitHub+Standards#GitHubStandards-Branchprotectionrule) before opening this pull request.

- [x] The name of the branch is meaningful and well formatted following the [standards](https://uclahs-cds.atlassian.net/wiki/spaces/BOUTROSLAB/pages/3189956/Code+Review+Best+Practice+on+GitHub+-+Check+List), using [AD_username (or 5 letters of AD if AD is too long)]-[brief_description_of_branch].
  
- [x] I have added the major changes included in this pull request to the `CHANGELOG.md` under the next release version or unreleased, and updated the date.

### CODE REVIEW

**Comment by nwiltsie** [comment]
(╯°□°)╯︵ ┻━┻

**Comment by nwiltsie** [comment]
Okay, at least this is confirmation that I'm not completely crazy:

https://github.com/uclahs-cds/tool-NFTest/blob/e0af6a54490f07a9b54ce2b000ddf78462211345/test/unit/test_NFTestAssert.py#L175-L188

```
Prior modification time was 2024-06-25 21:36:14.347513+00:00
Updated modification time is 2024-06-25 21:36:14.347513+00:00
```

**Comment by nwiltsie** [comment]
OKAY. I've re-run the pytest workflow [five times](https://github.com/uclahs-cds/tool-NFTest/actions/runs/9670748012/job/26680142016) and gotten five successes, so I think this is _finally_ stable and ready for review.

**Comment by yashpatel6** [comment]
I'll get to this in a day or two!

**Review by zhuchcn — APPROVED** [review]
Looks good to me! I like it when you check whether the pipeline output files are updated. I just don't understand what you meant by making `NFTestAssert` invisible to the outside world. Why is so and why do want want it in this way?

**Comment by nwiltsie** [comment]
@zhuchcn I didn't mean making the _class_ `NFTestAssert` invisible to the outside world, I meant that the _changes_ to the class should be invisible.

Put a little more formally and buzzword-y, I [encapsulated](https://en.wikipedia.org/wiki/Encapsulation_(computer_programming)) `NFTestAssert` to [hide the test assertion logic](https://en.wikipedia.org/wiki/Information_hiding) and [decouple](https://en.wikipedia.org/wiki/Coupling_(computer_programming)) the test running logic.

**Review by yashpatel6 — APPROVED** [review]
Looks good!

**Pull request merged**
